var hierarchy =
[
    [ "BaseException", "class_base_exception.html", [
      [ "AnimalConfigMissingException", "class_animal_config_missing_exception.html", null ],
      [ "CannotFarmException", "class_cannot_farm_exception.html", null ],
      [ "CannotFeedException", "class_cannot_feed_exception.html", null ],
      [ "CannotPlantException", "class_cannot_plant_exception.html", null ],
      [ "CannotPrintFarmException", "class_cannot_print_farm_exception.html", null ],
      [ "CannotPrintFieldException", "class_cannot_print_field_exception.html", null ],
      [ "CantBuyBangunan", "class_cant_buy_bangunan.html", null ],
      [ "CantFindNamaBangunan", "class_cant_find_nama_bangunan.html", null ],
      [ "CantSellBangunan", "class_cant_sell_bangunan.html", null ],
      [ "EmptyFoodSlot", "class_empty_food_slot.html", null ],
      [ "EmptyInventory", "class_empty_inventory.html", null ],
      [ "FullInv", "class_full_inv.html", null ],
      [ "InvalidAnimalChoice", "class_invalid_animal_choice.html", null ],
      [ "InvalidAnimalIDConfigException", "class_invalid_animal_i_d_config_exception.html", null ],
      [ "InvalidAnimalPriceConfigException", "class_invalid_animal_price_config_exception.html", null ],
      [ "InvalidAnimalTypeConfigException", "class_invalid_animal_type_config_exception.html", null ],
      [ "InvalidAnimalWeightConfigException", "class_invalid_animal_weight_config_exception.html", null ],
      [ "InvalidCarnivore", "class_invalid_carnivore.html", null ],
      [ "InvalidDirSimpan", "class_invalid_dir_simpan.html", null ],
      [ "InvalidEmptySlot", "class_invalid_empty_slot.html", null ],
      [ "InvalidFarmDimensionConfigException", "class_invalid_farm_dimension_config_exception.html", null ],
      [ "InvalidFieldDimensionConfigException", "class_invalid_field_dimension_config_exception.html", null ],
      [ "InvalidFilledSlot", "class_invalid_filled_slot.html", null ],
      [ "InvalidHerbivore", "class_invalid_herbivore.html", null ],
      [ "InvalidIndexMatrixArea", "class_invalid_index_matrix_area.html", null ],
      [ "InvalidInventorySpace", "class_invalid_inventory_space.html", null ],
      [ "InvalidMiscMoneyConfigException", "class_invalid_misc_money_config_exception.html", null ],
      [ "InvalidMiscWeightConfigException", "class_invalid_misc_weight_config_exception.html", null ],
      [ "InvalidNotHewan", "class_invalid_not_hewan.html", null ],
      [ "InvalidNotProduct", "class_invalid_not_product.html", null ],
      [ "InvalidNotTanaman", "class_invalid_not_tanaman.html", null ],
      [ "InvalidPanenAmount", "class_invalid_panen_amount.html", null ],
      [ "InvalidPanenAmountOver", "class_invalid_panen_amount_over.html", null ],
      [ "InvalidPanenIdx", "class_invalid_panen_idx.html", null ],
      [ "InvalidPathMuat", "class_invalid_path_muat.html", null ],
      [ "InvalidPlantChoice", "class_invalid_plant_choice.html", null ],
      [ "InvalidPlantDurationConfigException", "class_invalid_plant_duration_config_exception.html", null ],
      [ "InvalidPlantIDConfigException", "class_invalid_plant_i_d_config_exception.html", null ],
      [ "InvalidPlantPriceConfigException", "class_invalid_plant_price_config_exception.html", null ],
      [ "InvalidPlantTypeConfigException", "class_invalid_plant_type_config_exception.html", null ],
      [ "InvalidPositionMatrixArea", "class_invalid_position_matrix_area.html", null ],
      [ "InvalidProductIDConfigException", "class_invalid_product_i_d_config_exception.html", null ],
      [ "InvalidProductPriceConfigException", "class_invalid_product_price_config_exception.html", null ],
      [ "InvalidProductTypeConfigException", "class_invalid_product_type_config_exception.html", null ],
      [ "InvalidProductWeightConfigException", "class_invalid_product_weight_config_exception.html", null ],
      [ "InvalidRecipeIDConfigException", "class_invalid_recipe_i_d_config_exception.html", null ],
      [ "InvalidRecipePriceConfigException", "class_invalid_recipe_price_config_exception.html", null ],
      [ "InvalidRecipeQuantityConfigException", "class_invalid_recipe_quantity_config_exception.html", null ],
      [ "InvalidResponseToko", "class_invalid_response_toko.html", null ],
      [ "InvalidStorageDimensionConfigException", "class_invalid_storage_dimension_config_exception.html", null ],
      [ "InvalidSubResponse", "class_invalid_sub_response.html", null ],
      [ "InvalidTypePemain", "class_invalid_type_pemain.html", null ],
      [ "InventoryNotEnough", "class_inventory_not_enough.html", null ],
      [ "ItemQuantityToSellNotEnough", "class_item_quantity_to_sell_not_enough.html", null ],
      [ "MaterialNotEnough", "class_material_not_enough.html", null ],
      [ "MiscConfigMissingException", "class_misc_config_missing_exception.html", null ],
      [ "NoAnimal", "class_no_animal.html", null ],
      [ "NoAnimalInCage", "class_no_animal_in_cage.html", null ],
      [ "NoEmptySlot", "class_no_empty_slot.html", null ],
      [ "NoFoodInInventory", "class_no_food_in_inventory.html", null ],
      [ "NoHarvestableAnimal", "class_no_harvestable_animal.html", null ],
      [ "NoHarvestablePlant", "class_no_harvestable_plant.html", null ],
      [ "NoPlant", "class_no_plant.html", null ],
      [ "NotEatableSlot", "class_not_eatable_slot.html", null ],
      [ "NotEnoughGulden", "class_not_enough_gulden.html", null ],
      [ "PlantConfigMissingException", "class_plant_config_missing_exception.html", null ],
      [ "ProductConfigMissingException", "class_product_config_missing_exception.html", null ],
      [ "RecipeConfigMissingException", "class_recipe_config_missing_exception.html", null ],
      [ "SlotFilled", "class_slot_filled.html", null ],
      [ "StockTokoNotEnough", "class_stock_toko_not_enough.html", null ],
      [ "UserNamePemainTidakUnik", "class_user_name_pemain_tidak_unik.html", null ]
    ] ],
    [ "BaseParser", "class_base_parser.html", [
      [ "ParserHewan", "class_parser_hewan.html", null ],
      [ "ParserMisc", "class_parser_misc.html", null ],
      [ "ParserProduk", "class_parser_produk.html", null ],
      [ "ParserResep", "class_parser_resep.html", null ],
      [ "ParserTanaman", "class_parser_tanaman.html", null ]
    ] ],
    [ "GameManager", "class_game_manager.html", null ],
    [ "GameObject", "class_game_object.html", [
      [ "Bangunan", "class_bangunan.html", null ],
      [ "Hewan", "class_hewan.html", null ],
      [ "Product", "class_product.html", null ],
      [ "Tanaman", "class_tanaman.html", null ]
    ] ],
    [ "MatrixArea< T >", "class_matrix_area.html", null ],
    [ "MatrixArea< GameObject >", "class_matrix_area.html", null ],
    [ "MatrixArea< Hewan >", "class_matrix_area.html", null ],
    [ "MatrixArea< Tanaman >", "class_matrix_area.html", null ],
    [ "Pemain", "class_pemain.html", [
      [ "Petani", "class_petani.html", null ],
      [ "Peternak", "class_peternak.html", null ],
      [ "WaliKota", "class_wali_kota.html", null ]
    ] ],
    [ "Toko", "class_toko.html", null ]
];